<?php
return [
    'button'=> \NewInventor\Form\Field\Input::class,
    'checkBox' => \NewInventor\Form\Field\CheckBox::class,
    'file' => \NewInventor\Form\Field\Input::class,
    'hidden' => \NewInventor\Form\Field\Input::class,
    'image' => \NewInventor\Form\Field\Input::class,
    'password' => \NewInventor\Form\Field\Input::class,
    'radio' => \NewInventor\Form\Field\Input::class,
    'radioSet' => \NewInventor\Form\Field\RadioSet::class,
    'reset' => \NewInventor\Form\Field\Input::class,
    'submit' => \NewInventor\Form\Field\Input::class,
    'text' => \NewInventor\Form\Field\Input::class,
    'color' => \NewInventor\Form\Field\Input::class,
    'date' => \NewInventor\Form\Field\Input::class,
    'datetime' => \NewInventor\Form\Field\Input::class,
    'datetimeLocal' => \NewInventor\Form\Field\Input::class,
    'email' => \NewInventor\Form\Field\Input::class,
    'number' => \NewInventor\Form\Field\Input::class,
    'range' => \NewInventor\Form\Field\Input::class,
    'search' => \NewInventor\Form\Field\Input::class,
    'tel' => \NewInventor\Form\Field\Input::class,
    'time' => \NewInventor\Form\Field\Input::class,
    'url' => \NewInventor\Form\Field\Input::class,
    'month' => \NewInventor\Form\Field\Input::class,
    'week' => \NewInventor\Form\Field\Input::class,
    'select' => \NewInventor\Form\Field\Select::class,
    'textArea' => \NewInventor\Form\Field\TextArea::class,
    'checkBoxSet' => \NewInventor\Form\Field\CheckBoxSet::class,
];